- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/telegram_alerting.py
- buffalogs/impossible_travel/tests/test_email_alert.py
- buffalogs/impossible_travel/tests/test_telegram_alert.py
- buffalogs/requirements.txt
- config/buffalogs/alerting.json
- docs/alerting/telegram.md
**- Implemented the TelegramAlerting class.**
**-  Added corresponding test cases.**
**-  Included documentation for the new functionality.**
**- Used the requests library for handling HTTP requests and updated requirements.txt.**
- [telegram.md Documentation](https://github.com/certego/BuffaLogs/blob/8fe9e31507834ceb3b7eb587c1b0814681d59e6a/docs/alerting/telegram.md#create-your-bot)
- closes #137
> Add Telegram ALerter 

- buffalogs/impossible_travel/alerting/slack_alerter.py
- buffalogs/impossible_travel/tests/test_slack_alerter.py
- docs/alerting/slack.md
Hey @ManofWax !
I'm working on this issue [#136](https://github.com/certego/BuffaLogs/issues/136) just opened a draft pull request to let you know that I'm working on it and If there is any certain changes needed in it I'll also update that upon your request.
Thank You !
> Working on Slack Alert , its Docs and writing the test for the code as well

- config/nginx/conf.d/site.conf
- docker-compose.yaml
- docs/guides/adding_ssl_support.md
Hi @ManofWax 
Here's a preview of the documentation so far.
I added changes to docker-compose.yaml and site.conf files so you can examine it. I intend to revert it back before making the actual PR.
> Documentation adding support for ssl

- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/http_request.py
- buffalogs/impossible_travel/alerting/webhook.py
- buffalogs/impossible_travel/tests/test_http_request_alerting.py
- buffalogs/impossible_travel/tests/test_webhook_alerting.py
- buffalogs/requirements.txt
- config/buffalogs/alerting.json
- docs/alerting/http_request.md
- docs/alerting/webhooks.md
This is the corrected PR for #134. This branch checks out of `develop` and not the `main` branch.
> Feature add http and webhook alerting

- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/pushover_alerting.py
- buffalogs/impossible_travel/tests/test_alert_pushover.py
- config/buffalogs/alerting.json
In reference to the issue #135 
For full documentation on how to implement and use it refer to `docs/alerting/pushover.md`
- New Pushover alerting module implemented using requests
- Users can receive alerts on their Pushover Client(Mobile/Web)
- All tests are getting passed.
- Alerts being received on the pushover client
- 
@ManofWax looking forward to your insights !
> Added Pushover Alerter Functionality

- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/discord_alerting.py
- buffalogs/impossible_travel/tests/test_alert_discord.py
- config/buffalogs/alerting.json
- docs/alerting/discord.md
In reference to the issue #175 
- New Discord alerting module implemented using webhooks
- Users can receive alerts on their Discord Client(Mobile/Web)
- Documentation added on how to setup webhooks
@Lorygold @ManofWax looking forward to your insights !
> Added Discord Alerter

- buffalogs/impossible_travel/alerting/alert_factory.py
In reference to the issue #188 
@Lorygold
> Moved Slack Alerter Import to Top

- buffalogs/impossible_travel/static/css/style.css
- buffalogs/impossible_travel/templates/impossible_travel/base.html
- buffalogs/impossible_travel/templates/impossible_travel/homepage.html
**I have changed the dashboard homepage UI. It wasn't responsive before. I used bootstrap element to make the UI responsive and clean. (Issue: https://github.com/certego/BuffaLogs/issues/173)**
> Dashboard UI fix

- buffalogs/impossible_travel/ingestion/base_ingestion.py
- buffalogs/impossible_travel/ingestion/ingestion_factory.py
- buffalogs/impossible_travel/ingestion/opensearch_ingestion.py
- buffalogs/requirements.txt
- config/buffalogs/ingestion.json
- docker-compose.opensearch.yaml
Reference: #197 and #202 
Please review @Lorygold
> Added opensearch ingestion source

- frontend/lib/requestdata.ts
Refactored requestdata.ts by extracting the repeated date‑range formatting into a new formatDateRange() helper and centralizing the URL construction, fetch call, error checking, and JSON parsing in a single fetchData() function. Each of the four API methods (getUsersPieChart, getAlertsLineChart, getWorldMapChart, and getAlerts) now simply delegates to fetchData(), eliminating boilerplate, adhering to DRY, and making future endpoint additions far simpler to maintain.
> updated: consolidate duplicate date conversion and fetch logic

- buffalogs/impossible_travel/tests/test_views.py
- buffalogs/impossible_travel/views.py
In reference to the issue #243 
- Handling of date time logic is improved in functions `users_pie_chart_api , alerts_line_chart_api , world_map_chart_api , alerts_api , 
risk_score_api` by using `parse_datetime` to parse input date times rather than a fixed string.
- `make_aware` is also used to make sure the datetimes are timezone aware
@Lorygold @ManofWax looking forward to your insights !
> Refactor views.py

- buffalogs/buffalogs/urls.py
- buffalogs/impossible_travel/dashboard/charts.py
- buffalogs/impossible_travel/static/css/users.css
- buffalogs/impossible_travel/static/js/users.js
- buffalogs/impossible_travel/templates/impossible_travel/users.html
- buffalogs/impossible_travel/tests/test_views.py
- buffalogs/impossible_travel/views.py
Ref: #173 
In this pr, I have worked on the **backend and frontend** side where I created some useful charts in `charts.py` to help detect user login behavior. I also developed an API that serves JSON data for all these charts. Additionally, I wrote test cases to ensure the APIs are functioning correctly.
On the frontend, I made modifications to `users.html`, `users.js`, and `users.css` by removing the previous content entirely. However, I have not removed any APIs or functions related to the previous users functionality, as I believe we might repurpose them in the future by creating a separate page.
---
**Dashboard View**
> [Screencast from 2025-05-01 18-30-24.webm](https://github.com/user-attachments/assets/8256fd57-fa6a-4b83-a53d-0b6c0f72dd38)
---
Hi @Lorygold , Please review this PR …
> feat: User Login Activity Dashboard

- docker-compose.yaml
- frontend/.dockerignore
- frontend/Dockerfile
In this PR, as outlined in issue #251, I successfully  dockerized Node JS : frontend. 
- Created  two files Dockerfile and .dockerignore at frontend/
-  updated docker-compose.yaml 
[Screencast from 2025-04-19 16-16-59.webm](https://github.com/user-attachments/assets/77a7c41a-aaca-46b3-80ed-b2c229384b52)
While testing the docker I got some error as mention in screenshots below. However Running the command `docker start buffalogs_frontend` make runs smoothly and exposing it on 3000 port as mention above in UI. Probably the error occur because of my own local system.
Please review this PR, @Lorygold  @ManofWax.  If there are any suggestions or changes needed, I would be truly grateful for your guidance. Thank you for your time and support
> feat:  Dockerized Node Js 

- buffalogs/impossible_travel/templates/impossible_travel/homepage.html
- buffalogs/impossible_travel/views.py
This PR solves the bug as mention in this #279 issue
**Before**
>  ![Screenshot from 2025-05-13 16-11-04](https://github.com/user-attachments/assets/47558d9d-17f1-4a05-9096-5d48c9ec5b3b)
**After**
>  ![Screenshot from 2025-05-13 16-19-11](https://github.com/user-attachments/assets/5cf7e568-0b6e-446c-b7b7-3848ff13065f)
@Lorygold  please review this pr.
> Bug_fix/frontend: Homepage

- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/googlechat_alerting.py
- buffalogs/impossible_travel/tests/test_alert_googlechat.py
- config/buffalogs/alerting.json
- docs/alerting/googlechat.md
Resolves #288 
- New alerter implemented : GoogleChat
- Documentation added on how to set it up
> Adds GoogleChat Alerter

- frontend/Dockerfile
> Fixed healtcheck in the frontened Docker container

- buffalogs/impossible_travel/alerting/alert_factory.py
- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/rocketchat_alerting.py
- buffalogs/impossible_travel/tests/test_alert_rocketchat.py
- config/buffalogs/alerting.json
- docs/alerting/rocketchat.md
Resolves #290 
- New alerter implemented : RocketChat
- Documentation added on how to set it up
> Adds RocketChat Alerter

- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/discord_alerting.py
- buffalogs/impossible_travel/alerting/email_alerting.py
- buffalogs/impossible_travel/alerting/googlechat_alerting.py
- buffalogs/impossible_travel/alerting/mattermost_alerting.py
- buffalogs/impossible_travel/alerting/microsoft_teams_alerting.py
- buffalogs/impossible_travel/alerting/pushover_alerting.py
- buffalogs/impossible_travel/alerting/rocketchat_alerting.py
- buffalogs/impossible_travel/alerting/slack_alerting.py
- buffalogs/impossible_travel/alerting/telegram_alerting.py
- buffalogs/impossible_travel/tests/test_alert_discord.py
- buffalogs/impossible_travel/tests/test_alert_email.py
- buffalogs/impossible_travel/tests/test_alert_googlechat.py
- buffalogs/impossible_travel/tests/test_alert_mattermost.py
- buffalogs/impossible_travel/tests/test_alert_microsoft_teams.py
- buffalogs/impossible_travel/tests/test_alert_pushover.py
- buffalogs/impossible_travel/tests/test_alert_rocketchat.py
- buffalogs/impossible_travel/tests/test_alert_slack.py
- buffalogs/impossible_travel/tests/test_alert_telegram.py
Resolves #308 
- Setup of tests made easier by directly importing config from `alerting.json`. User can just update the `alerting.json` to run the tests.
- New tests added to cover edge cases,such as:
- `test_no_alerts` : Test that no alerts are sent when there are no alerts to notify
- `test_improper_config` :  Test that an error is raised if the configuration is not correct
- `test_alert_network_failure` : Test that alert is not marked as notified if there are any Network Fails
- `email_alerting.py` updated to handle missing configs
> Comprehensive Testing

- buffalogs/impossible_travel/alerting/base_alerting.py
- buffalogs/impossible_travel/alerting/discord_alerting.py
- buffalogs/impossible_travel/alerting/email_alerting.py
- buffalogs/impossible_travel/alerting/googlechat_alerting.py
- buffalogs/impossible_travel/alerting/mattermost_alerting.py
- buffalogs/impossible_travel/alerting/microsoft_teams_alerting.py
- buffalogs/impossible_travel/alerting/pushover_alerting.py
- buffalogs/impossible_travel/alerting/rocketchat_alerting.py
- buffalogs/impossible_travel/alerting/slack_alerting.py
- buffalogs/impossible_travel/alerting/telegram_alerting.py
- buffalogs/impossible_travel/tests/test_alert_discord.py
- buffalogs/impossible_travel/tests/test_alert_email.py
- buffalogs/impossible_travel/tests/test_alert_googlechat.py
- buffalogs/impossible_travel/tests/test_alert_mattermost.py
- buffalogs/impossible_travel/tests/test_alert_microsoft_teams.py
- buffalogs/impossible_travel/tests/test_alert_pushover.py
- buffalogs/impossible_travel/tests/test_alert_rocketchat.py
- buffalogs/impossible_travel/tests/test_alert_slack.py
- buffalogs/impossible_travel/tests/test_alert_telegram.py
Resolves #314 
- `alert_message_formatter` added in `BaseAlerting` class to take in the alert as an argument and return the formatted alert title and alert description
- All the alerting modules have been updated to ensure consistent alert message.
- All the tests for alerting modules have been updated.
> Alert Message Formatter

- .github/workflows/buffacli_CI.yml
- CHANGELOG.md
> Fixed BuffaCLI CI for tests with pytest

- buffacli/src/buffacli/exception_handlers.py
- buffacli/src/buffacli/requests.py
Defined a base exception handler class and created a generic request exception handler that prints out the error without a traceback and exits the program
solves #392
> Feature [buffacli] Added Generic Request Exception Handling

- .github/dependabot.yml
- CHANGELOG.md
Resolves #397 
and dependabot PR: #362
> Removed deprecated reviewers field from dependabot

- buffacli/src/buffacli/buffacli.py
- buffacli/src/buffacli/commands/query/__init__.py
- buffacli/src/buffacli/commands/query/ideas.txt
- buffacli/src/buffacli/commands/query/logins.py
- buffacli/src/buffacli/config.json
- buffacli/src/buffacli/config.py
- buffacli/src/buffacli/exception_handlers.py
- buffacli/src/buffacli/export.py
- buffacli/src/buffacli/formatters.py
- buffacli/src/buffacli/globals.py
- buffacli/src/buffacli/models/__init__.py
- buffacli/src/buffacli/models/query.py
- buffacli/src/buffacli/render.py
- buffacli/src/buffacli/requests.py
In addition to having a handler for certain exceptions #393, I add verbose printing that prints out extra information depending on the verbose level (#392)
> Feature add verbose printing

- buffalogs/buffalogs/settings/.env
- buffalogs/buffalogs/urls.py
- buffalogs/impossible_travel/models.py
- buffalogs/impossible_travel/views/logins.py
Solves #409.
Created a new view function for querying login data
> Feature add log query

- docs/alerting/discord.md
- docs/alerting/email.md
- docs/alerting/googlechat.md
- docs/alerting/mattermost.md
- docs/alerting/microsoft_teams.md
- docs/alerting/pushover.md
- docs/alerting/rocketchat.md
- docs/alerting/slack.md
- docs/alerting/telegram.md
- docs/guides/development/complete_guide_for_developers.md
Resolves #407 
- Standardize and Improve docs related to alerting
- Expand the developer wiki
- Address common questions
- Improve the overall documentation
> Documentation Uniformity

- buffalogs/impossible_travel/tasks.py
As mention in the issue #420 , I solve the issue, by adding TaskSettings, tracking to BuffalogsCleanModelsPeriodicallyTask for consistency with other tasks
> feat:  Added BuffalogsCleanModelsPeriodicallyTask in TaskSettings model
